name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "Natorious"
          replace: "SupRemE_AnanD"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Owner Updated'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: EAGLEBOY-OP
          commit_user_email: baapterabcbc@gmail.com
          commit_author: Eagle-OP <baapterabcbc@gmail.com>
